# security repo sync
apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: platform-security
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/harideveloper/platform-security.git
    branch: master
    dir: /
    auth: none
