# ops repo sync
apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: platform-ops
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/harideveloper/platform-ops.git
    branch: main
    dir: /
    auth: none
