kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding_platform_ops
  namespace: platform_ops
subjects:
- kind: ServiceAccount
  name: ns-reconciler-platform-ops
  namespace: config-management-system
roleRef:
  kind: Role
  name: role_platform_ops
  apiGroup: rbac.authorization.k8s.io