# ops rb 
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-platform-ops
  namespace: platform-ops
subjects:
- kind: ServiceAccount
  name: ns-reconciler-platform-ops
  namespace: config-management-system
roleRef:
  kind: Role
  name: role-platform-ops
  apiGroup: rbac.authorization.k8s.io